# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        BDE-UTC : Portail des associations
    viewport:     "width=device-width, initial-scale=1.0"
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       noindex, nofollow

  stylesheets:    ["//fonts.googleapis.com/css?family=Raleway:900", bootstrap.min.css, main.css, bootstrap-responsive.min.css, font-awesome.min.css, typeahead.js-bootstrap.css]

  javascripts:    [jquery-1.7.2.min.js, bootstrap.min.js, main.js, typeahead.bundle.min.js] 

  has_layout:     true
  layout:         layout
