charte_locaux:
  class: sfDoctrineRouteCollection
  options:
    model:                CharteLocaux
    module:               charte_locaux
    prefix_path:          /charte_locaux
    column:               id
    with_wildcard_routes: true

infojob:
  url: /infojob
  param: { module: infojob, action: index }

info_job_signalement:
  class: sfDoctrineRouteCollection
  options:
    model:                InfoJobSignalement
    module:               infojob_signalement
    prefix_path:          /infojob_signalement
    column:               id
    with_wildcard_routes: true


info_job_offre:
  class: sfDoctrineRouteCollection
  options:
    model:                InfoJobOffre
    module:               infojob_offre
    prefix_path:          /infojob/offre
    column:               id
    with_wildcard_routes: true

info_job_disponibilite:
  class: sfDoctrineRouteCollection
  options:
    model:                InfoJobDisponibilite
    module:               infojob_disponibilite
    prefix_path:          /infojob/disponibilite
    column:               id
    with_wildcard_routes: true

info_job_categorie:
  class: sfDoctrineRouteCollection
  options:
    model:                InfoJobCategorie
    module:               infojob_categorie
    prefix_path:          /infojob/categorie
    column:               id
    with_wildcard_routes: true

service:
  class: sfDoctrineRouteCollection
  options:
    model:                Service
    module:               service
    prefix_path:          /service
    column:               id
    with_wildcard_routes: true

partenaire:
  class: sfDoctrineRouteCollection
  options:
    model:                Partenaire
    module:               partenaire
    prefix_path:          /partenaire
    column:               id
    with_wildcard_routes: true

carnetAvantage:
  class: sfDoctrineRouteCollection
  options:
    model:                CarnetAvantages
    module:               carnetAvantage
    prefix_path:          /carnetAvantage
    column:               id
    with_wildcard_routes: true

weekmail:
  url: /weekmail
  param: { module: weekmail, action: index }
weekmail_show:
  url:   /article/show/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: show }
  options: { model: Weekmail, type: object }
weekmail_edit:
  url:  /article/edit/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: edit }
  options: { model: Weekmail, type: object }
weekmail_update:
  url:  /weekmail/update/:id
  param: { module: weekmail, action: update }
weekmail_delete:
  url:  /weekmail/delete/:id
  param: { module: weekmail, action: delete }
weekmail_create:
  url: /weekmail/create
  param: { module: weekmail, action: create }
weekmail_new:
  url: /weekmail/new
  param: { module: weekmail, action: new }
weekmail_publish:
  url: /weekmail/publish/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: publish }
  options: { model: Weekmail, type: object }
weekmail_refuse:
  url: /weekmail/refuse/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: refuse }
  options: { model: Article, type: object }
weekmail_accept:
  url: /weekmail/accept/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: accept }
  options: { model: Article, type: object }
weekmail_refuse_event:
  url: /weekmail/refuse_event/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: refuseEvent }
  options: { model: Event, type: object }
weekmail_accept_event:
  url: /weekmail/accept_event/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: acceptEvent }
  options: { model: Event, type: object }
weekmail_delete_article:
  url:  /weekmail/delete_article/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: deleteArticle }
  options: { model: WeekmailArticle, type: object }
weekmail_html:
  url: /weekmail/html/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: html }
  options: { model: Weekmail, type: object }

charte_info:
  class: sfDoctrineRouteCollection
  options:
    model:                CharteInfo
    module:               charte_info
    prefix_path:          /chartes
    column:               id
    with_wildcard_routes: true

cotisants:
  url: /cotisants
  param: { module: cotisants, action: index }

cotisants_edit:
  url: /cotisants/edit
  param: { module: cotisants, action: edit }
  
cotisants_cotisation:
  url: /cotisants/cotisation
  param: { module: cotisants, action: cotisation }

cas:
  url: /cas
  param: { module: utcCas, action: login }

cas_logout:
  url: /cas/logout
  param: { module: utcCas, action: logout }

#reservation
reservation:
  url: /reservation
  param: { module: reservation, action: index }

reservation_gestion:
  url: /reservation/gestion
  param: { module: reservation, action: gestion }  
  
reservation_gestion_delete:
  url: /reservation/gestion/delete
  param: { module: reservation, action: gestionDelete }

reservation_gestion_edit:
  url: /reservation/gestion/edit
  param: { module: reservation, action: gestionEdit }
  
reservation_gestion_salle_list:
  url: /reservation/gestion/salleList
  param: { module: reservation, action: getSalleByPole }
  
reservation_gestion_id:
  url: /reservation/gestion/:id
  param: { module: reservation, action: gestionId }

reservation_validation:
  url: /reservation/validation
  param: { module: reservation, action: validation }

reservation_validation_id:
  url: /reservation/validation/:id
  param: { module: reservation, action: validation }

reservation_validation_valid:
  url: /reservation/validation/valid/:id
  param: { module: reservation, action: validationValid }

reservation_salle:
  url: /reservation/salle
  param: { module: reservation, action: salle }

reservation_salle_new:
  url: /reservation/salle/new
  param: { module: reservation, action: salleNew }

reservation_salle_delete:
  url: /reservation/salle/delete/:id
  param: { module: reservation, action: salleDelete }

reservation_creneauoff:
  url: /reservation/creneauoff
  param: { module: reservation, action: creneauoff }

reservation_salle_update:
  url: /reservation/salle/update/:id
  param: { module: reservation, action: salleUpdate }

reservations_statSalle:
  url: /reservation/statistiques/salles.:sf_format
  param: { module: reservation, action: statSalle }
  requirements:
    sf_format: (json)

reservations_statJour:
  url: /reservation/statistiques/jours.:sf_format
  param: { module: reservation, action: statJour }
  requirements:
    sf_format: (json)

reservations_statAsso:
  url: /reservation/statistiques/assos.:sf_format
  param: { module: reservation, action: statAsso }
  requirements:
    sf_format: (json)

reservations_statPole:
  url: /reservation/statistiques/poles.:sf_format
  param: { module: reservation, action: statPole }
  requirements:
    sf_format: (json)

reservations_statMois:
  url: /reservation/statistiques/mois.:sf_format
  param: { module: reservation, action: statMois }
  requirements:
    sf_format: (json)

reservation_statistiques:
  url: /reservation/statistiques
  param: { module: reservation, action: statistiques }

reservations_json:
  url: /reservations.:sf_format/:pole/:salle
  param: { module: reservation, action: reservations }
  requirements:
    sf_format: (?:html|json)

#Cotisations extérieures
exterieurs:
  url: /exterieurs
  param: { module: exterieurs, action: index }

exterieurs_edit:
  url: /exterieurs/edit
  param: { module: exterieurs, action: edit }

# default rules
homepage:
  url:   /
  param: { module: home, action: index }
